openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
tags:
  -
    name: Endpoints
    description: ''
  -
    name: 'Resident Management'
    description: "\nAPIs for managing the barangay resident database."
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your API token from the Barangay Administrator.'
security:
  -
    default: []
paths:
  /api/webhooks/stripe:
    post:
      summary: ''
      operationId: postApiWebhooksStripe
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 019dc503-8ba8-7386-96e4-55db5a62fee5
                  name: 'Juan Dela Cruz'
                  email: deguzman.ralphethan@student.auf.edu.ph
                  email_verified_at: null
                  created_at: '2026-04-25T14:20:37.000000Z'
                  updated_at: '2026-04-25T14:20:37.000000Z'
                properties:
                  id:
                    type: string
                    example: 019dc503-8ba8-7386-96e4-55db5a62fee5
                  name:
                    type: string
                    example: 'Juan Dela Cruz'
                  email:
                    type: string
                    example: deguzman.ralphethan@student.auf.edu.ph
                  email_verified_at:
                    type: string
                    example: null
                    nullable: true
                  created_at:
                    type: string
                    example: '2026-04-25T14:20:37.000000Z'
                  updated_at:
                    type: string
                    example: '2026-04-25T14:20:37.000000Z'
      tags:
        - Endpoints
  /api/weather:
    get:
      summary: 'Fetch live weather data for Angeles City from an External API'
      operationId: fetchLiveWeatherDataForAngelesCityFromAnExternalAPI
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Weather data fetched successfully from Open-Meteo.'
                  location: 'Angeles City, Pampanga'
                  temperature: 29.8°C
                  windspeed: '7.8 km/h'
                  is_day: 'Yes'
                  raw_data:
                    time: '2026-04-28T08:45'
                    interval: 900
                    temperature: 29.8
                    windspeed: 7.8
                    winddirection: 105
                    is_day: 1
                    weathercode: 1
                properties:
                  message:
                    type: string
                    example: 'Weather data fetched successfully from Open-Meteo.'
                  location:
                    type: string
                    example: 'Angeles City, Pampanga'
                  temperature:
                    type: string
                    example: 29.8°C
                  windspeed:
                    type: string
                    example: '7.8 km/h'
                  is_day:
                    type: string
                    example: 'Yes'
                  raw_data:
                    type: object
                    properties:
                      time:
                        type: string
                        example: '2026-04-28T08:45'
                      interval:
                        type: integer
                        example: 900
                      temperature:
                        type: number
                        example: 29.8
                      windspeed:
                        type: number
                        example: 7.8
                      winddirection:
                        type: integer
                        example: 105
                      is_day:
                        type: integer
                        example: 1
                      weathercode:
                        type: integer
                        example: 1
      tags:
        - Endpoints
  /api/residents:
    get:
      summary: 'List all residents'
      operationId: listAllResidents
      description: "Returns a paginated list of all residents in the barangay.\n* @authenticated"
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'Residents retrieved successfully.'
                  data:
                    current_page: 1
                    data:
                      -
                        id: 019dc54c-aa04-704a-bcd2-49b05b982a07
                        first_name: test
                        middle_name: t
                        last_name: test1
                        suffix: null
                        date_of_birth: '2019-01-29'
                        gender: Male
                        civil_status: Single
                        purok_or_street: 'FPH 11'
                        contact_number: '09288736929'
                        is_registered_voter: 0
                        occupation: Worker
                        residency_status: Active
                      -
                        id: 019dc6ab-5cc6-7019-b124-e0ae3c50b7a9
                        first_name: Maria
                        middle_name: null
                        last_name: 'Dela Cruz'
                        suffix: null
                        date_of_birth: '1985-10-16'
                        gender: Female
                        civil_status: Single
                        purok_or_street: 'FPH 1 brgy2'
                        contact_number: '09288736929'
                        is_registered_voter: 0
                        occupation: Housewife
                        residency_status: Active
                      -
                        id: f6d089f8-e1c6-4c42-b534-f45a241f8d2e
                        first_name: Test3
                        middle_name: null
                        last_name: 3test
                        suffix: null
                        date_of_birth: '2003-03-05'
                        gender: Other
                        civil_status: Single
                        purok_or_street: 'FPH 1 brgy24'
                        contact_number: '09288736929'
                        is_registered_voter: 0
                        occupation: null
                        residency_status: Active
                    first_page_url: 'http://localhost:8000/api/residents?page=1'
                    from: 1
                    last_page: 1
                    last_page_url: 'http://localhost:8000/api/residents?page=1'
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        page: null
                        active: false
                      -
                        url: 'http://localhost:8000/api/residents?page=1'
                        label: '1'
                        page: 1
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        page: null
                        active: false
                    next_page_url: null
                    path: 'http://localhost:8000/api/residents'
                    per_page: 15
                    prev_page_url: null
                    to: 3
                    total: 3
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Residents retrieved successfully.'
                  data:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      data:
                        type: array
                        example:
                          -
                            id: 019dc54c-aa04-704a-bcd2-49b05b982a07
                            first_name: test
                            middle_name: t
                            last_name: test1
                            suffix: null
                            date_of_birth: '2019-01-29'
                            gender: Male
                            civil_status: Single
                            purok_or_street: 'FPH 11'
                            contact_number: '09288736929'
                            is_registered_voter: 0
                            occupation: Worker
                            residency_status: Active
                          -
                            id: 019dc6ab-5cc6-7019-b124-e0ae3c50b7a9
                            first_name: Maria
                            middle_name: null
                            last_name: 'Dela Cruz'
                            suffix: null
                            date_of_birth: '1985-10-16'
                            gender: Female
                            civil_status: Single
                            purok_or_street: 'FPH 1 brgy2'
                            contact_number: '09288736929'
                            is_registered_voter: 0
                            occupation: Housewife
                            residency_status: Active
                          -
                            id: f6d089f8-e1c6-4c42-b534-f45a241f8d2e
                            first_name: Test3
                            middle_name: null
                            last_name: 3test
                            suffix: null
                            date_of_birth: '2003-03-05'
                            gender: Other
                            civil_status: Single
                            purok_or_street: 'FPH 1 brgy24'
                            contact_number: '09288736929'
                            is_registered_voter: 0
                            occupation: null
                            residency_status: Active
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: 019dc54c-aa04-704a-bcd2-49b05b982a07
                            first_name:
                              type: string
                              example: test
                            middle_name:
                              type: string
                              example: t
                            last_name:
                              type: string
                              example: test1
                            suffix:
                              type: string
                              example: null
                              nullable: true
                            date_of_birth:
                              type: string
                              example: '2019-01-29'
                            gender:
                              type: string
                              example: Male
                            civil_status:
                              type: string
                              example: Single
                            purok_or_street:
                              type: string
                              example: 'FPH 11'
                            contact_number:
                              type: string
                              example: '09288736929'
                            is_registered_voter:
                              type: integer
                              example: 0
                            occupation:
                              type: string
                              example: Worker
                            residency_status:
                              type: string
                              example: Active
                      first_page_url:
                        type: string
                        example: 'http://localhost:8000/api/residents?page=1'
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      last_page_url:
                        type: string
                        example: 'http://localhost:8000/api/residents?page=1'
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            page: null
                            active: false
                          -
                            url: 'http://localhost:8000/api/residents?page=1'
                            label: '1'
                            page: 1
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            page: null
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                              nullable: true
                            label:
                              type: string
                              example: '&laquo; Previous'
                            page:
                              type: string
                              example: null
                              nullable: true
                            active:
                              type: boolean
                              example: false
                      next_page_url:
                        type: string
                        example: null
                        nullable: true
                      path:
                        type: string
                        example: 'http://localhost:8000/api/residents'
                      per_page:
                        type: integer
                        example: 15
                      prev_page_url:
                        type: string
                        example: null
                        nullable: true
                      to:
                        type: integer
                        example: 3
                      total:
                        type: integer
                        example: 3
      tags:
        - 'Resident Management'
    post:
      summary: 'Register a new resident'
      operationId: registerANewResident
      description: 'Creates a new resident record in the database.'
      parameters: []
      responses: {  }
      tags:
        - 'Resident Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'The first name of the resident.'
                  example: Juan
                middle_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: amniihfqcoynlazghdtqt
                  nullable: true
                last_name:
                  type: string
                  description: 'The last name.'
                  example: 'Dela Cruz'
                suffix:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: auydlsmsjuryvojcybzvr
                  nullable: true
                date_of_birth:
                  type: date
                  description: 'Format: YYYY-MM-DD.'
                  example: '1990-05-15'
                gender:
                  type: string
                  description: 'Must be Male, Female, or Other.'
                  example: Male
                civil_status:
                  type: string
                  description: 'Single, Married, Widowed, or Legally Separated.'
                  example: Single
                purok_or_street:
                  type: string
                  description: 'Street address.'
                  example: 'Purok 1'
                contact_number:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vazjrcnfbaqywuxhgjjmz
                  nullable: true
                is_registered_voter:
                  type: boolean
                  description: ''
                  example: true
                  nullable: true
                occupation:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: uxjubqouzswiwxtrkimfc
                  nullable: true
                residency_status:
                  type: string
                  description: ''
                  example: Moved
                  enum:
                    - Active
                    - Moved
                    - Deceased
                  nullable: true
              required:
                - first_name
                - last_name
                - date_of_birth
                - gender
                - civil_status
                - purok_or_street
  '/api/residents/{id}':
    get:
      summary: 'Get a specific resident'
      operationId: getASpecificResident
      description: "Retrieves the complete profile of a single resident using their UUID.\n* @authenticated"
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'Resident details retrieved.'
                  data:
                    id: 019dc54c-aa04-704a-bcd2-49b05b982a07
                    first_name: test
                    middle_name: t
                    last_name: test1
                    suffix: null
                    date_of_birth: '2019-01-29'
                    gender: Male
                    civil_status: Single
                    purok_or_street: 'FPH 11'
                    contact_number: '09288736929'
                    is_registered_voter: 0
                    occupation: Worker
                    residency_status: Active
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Resident details retrieved.'
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 019dc54c-aa04-704a-bcd2-49b05b982a07
                      first_name:
                        type: string
                        example: test
                      middle_name:
                        type: string
                        example: t
                      last_name:
                        type: string
                        example: test1
                      suffix:
                        type: string
                        example: null
                        nullable: true
                      date_of_birth:
                        type: string
                        example: '2019-01-29'
                      gender:
                        type: string
                        example: Male
                      civil_status:
                        type: string
                        example: Single
                      purok_or_street:
                        type: string
                        example: 'FPH 11'
                      contact_number:
                        type: string
                        example: '09288736929'
                      is_registered_voter:
                        type: integer
                        example: 0
                      occupation:
                        type: string
                        example: Worker
                      residency_status:
                        type: string
                        example: Active
      tags:
        - 'Resident Management'
    patch:
      summary: 'Update a resident'
      operationId: updateAResident
      description: "Partially update an existing resident's information. You only need to send the fields you wish to change."
      parameters: []
      responses: {  }
      tags:
        - 'Resident Management'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vmqeopfuudtdsufvyvddq
                middle_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: amniihfqcoynlazghdtqt
                  nullable: true
                last_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: qxbajwbpilpmufinllwlo
                suffix:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: auydlsmsjuryvojcybzvr
                  nullable: true
                date_of_birth:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2026-04-28T00:45:29'
                gender:
                  type: string
                  description: ''
                  example: Female
                  enum:
                    - Male
                    - Female
                    - Other
                civil_status:
                  type: string
                  description: ''
                  example: Widowed
                  enum:
                    - Single
                    - Married
                    - Widowed
                    - 'Legally Separated'
                purok_or_street:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: byickznkygloigmkwxphl
                contact_number:
                  type: string
                  description: 'The new contact number.'
                  example: '09123456789'
                  nullable: true
                is_registered_voter:
                  type: boolean
                  description: ''
                  example: true
                occupation:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: uxjubqouzswiwxtrkimfc
                  nullable: true
                residency_status:
                  type: string
                  description: ''
                  example: Active
                  enum:
                    - Active
                    - Moved
                    - Deceased
    delete:
      summary: 'Delete a resident'
      operationId: deleteAResident
      description: 'Permanently removes a resident from the database.'
      parameters: []
      responses: {  }
      tags:
        - 'Resident Management'
    parameters:
      -
        in: path
        name: id
        description: 'The UUID of the resident.'
        example: 019dc54c-aa04-704a-bcd2-49b05b982a07
        required: true
        schema:
          type: string
